### ISSUE TITLE
error with Fun_with_HBase.xml

### ISSUE THREAD

**Issue by ashitabh** [hortonworks-gallery/nifi-templates#5]
Flow created using template is throwing  following error for HBase write  (PutHbaseCell and PutHbaseJson). I have updated only controller setting ,and haven't done any change in workflow created by template

apache.nifi.hbase.PutHBaseJSON PutHBaseJSON[id=6e1f5223-c332-48bb-b261-3f6f50396e0a] **Missing row id for FlowFile StandardFlowFileRecord**[uuid=b9e3cd66-dca7-4106-b634-d19e6ce608a8,claim=StandardContentClaim [resourceClaim=StandardResourceClaim[id=1463509861921-1, container=default, section=1], offset=49106, length=50],offset=0,name=1086787873266535,size=50]; routing to failure

**Comment by JPercivall** [comment]
Hello @ashitabh, 
Thank you for bringing this up. I reached out to the creator of the template and this issue actually came up before there was an updated Template made. I've update the template on master of this repo. Just pull the latest commit and let me know if it solves your problem.

**Comment by ashitabh** [comment]
thanks , it's working now
